#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=gcc
VERSION=$GCC_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/gcc/gcc-$VERSION/$TARFILE"
mSBU=1100

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    ln -sf gthr-posix.h libgcc/gthr-default.h

    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    ../libstdc++-v3/configure            \
        CXXFLAGS="-g -O2 -D_GNU_SOURCE"  \
        --prefix=/usr                    \
        --disable-multilib               \
        --disable-nls                    \
        --host=$(uname -m)-lfs-linux-gnu \
        --disable-libstdcxx-pch >>"$LOGFILE" 2>&1
}

build()
{
    cd $BUILD_PATH

    make -j1 >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
