#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=bison
VERSION=$BISON_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/bison/$TARFILE"
mSBU=300

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    BUILD_PATH=$(pwd)

    ./configure --prefix=/usr \
        --docdir=/usr/share/doc/bison-$VERSION >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
