#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=binutils
VERSION=$BINUTILS_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/binutils/$TARFILE"
mSBU=1000

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)
    ../configure \
		--prefix=$LFS/tools   \
        --with-sysroot="$LFS" \
        --target="$LFS_TGT"   \
        --disable-nls         \
        --disable-werror >>"$LOGFILE" 2>&1
}

build_install()
{
    cd $BUILD_PATH
    # Force one job to work around potential build issue
    make install -j1 >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
