#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=binutils
VERSION=${BINUTILS_VER}
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/binutils/$TARFILE"
mSBU=1000

configure()
{
    cd "$TMP"/"$NAME"-"$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)
    ../configure --prefix=/tools        \
            --with-sysroot="$LFS"       \
            --with-lib-path=/tools/lib  \
            --target="$LFS_TGT"         \
            --disable-nls               \
            --disable-werror >>"$LOGFILE" 2>&1
}

post_build()
{
    {
    case $(uname -m) in
        x86_64) mkdir -vp /tools/lib && ln -sv lib /tools/lib64 ;;
    esac
    } >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
