#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=linux
VERSION=$LINUX_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="https://www.kernel.org/pub/linux/kernel/v5.x/$TARFILE"
mSBU=100

configure()
{
    # Set only the build-path
    BUILD_PATH="$WORKBENCH/$NAME-$VERSION" 
}

build()
{
    {
    cd "$BUILD_PATH"
    make mrproper
    } >>"$LOGFILE" 2>&1
}

build_install()
{
    {
    cd "$BUILD_PATH"

    make headers
    find usr/include -name '.*' -delete
    rm -v usr/include/Makefile
    cp -rv usr/include $LFS/usr
    } >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
