#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=gcc
VERSION=$GCC_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/gcc/gcc-8.2.0/$TARFILE"
mSBU=500

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build

    BUILD_PATH=$(pwd)

    ../libstdc++-v3/configure --host="$LFS_TGT"                     \
        --prefix=/tools                                             \
        --disable-multilib                                          \
        --disable-nls                                               \
        --disable-libstdcxx-threads                                 \
        --disable-libstdcxx-pch                                     \
        --with-gxx-include-dir=/tools/"$LFS_TGT"/include/c++/$VERSION >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
