#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=m4
VERSION=$M4_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/m4/$TARFILE"
mSBU=200

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    BUILD_PATH=$(pwd)

    ./configure --prefix=/usr \
        --host=$LFS_TGT \
        --build=$(build-aux/config.guess) >>"$LOGFILE" 2>&1
}

build_install()
{
    cd "$BUILD_PATH"
    make $MAKE_JOBS DESTDIR=$LFS install >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
