#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=ncurses
VERSION=$NCURSES_VER
TARFILE=$NAME-$VERSION.tar.gz
FETCH_URL="http://ftp.gnu.org/gnu/ncurses/$TARFILE"
mSBU=700

patchup()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    sed -i s/mawk// configure
}

pre_configure()
{
    # First build the 'tic' program on the build host
    cd "$WORKBENCH/$NAME-$VERSION"

    {
    mkdir build
    pushd build
    ../configure
    make -C include
    make -C progs tic
    popd
    } >>"$LOGFILE" 2>&1
}

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    BUILD_PATH=$(pwd)

    ./configure                          \
            --prefix=/usr                \
            --host=$LFS_TGT              \
            --build=$(./config.guess)    \
            --mandir=/usr/share/man      \
            --with-manpage-format=normal \
            --with-shared                \
            --without-debug              \
            --without-ada                \
            --without-normal             \
            --enable-widec >>"$LOGFILE" 2>&1
}

build_install()
{
    cd "$WORKBENCH/$NAME-$VERSION"

    make $MAKE_JOBS DESTDIR=$LFS TIC_PATH=$(pwd)/build/progs/tic install >>"$LOGFILE" 2>&1
}

post_install()
{
    echo "INPUT(-lncursesw)" > $LFS/usr/lib/libncurses.so
}

source "$(dirname "$0")"/../common/common_exec
