#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=coreutils
VERSION=$COREUTILS_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/coreutils/$TARFILE"
mSBU=600

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    BUILD_PATH=$(pwd)

    ./configure                           \
        --prefix=/usr                     \
        --host=$LFS_TGT                   \
        --build=$(build-aux/config.guess) \
        --enable-install-program=hostname \
        --enable-no-install-program=kill,uptime >>"$LOGFILE" 2>&1
}

build_install()
{
    cd "$BUILD_PATH"
    make $MAKE_JOBS DESTDIR=$LFS install >>"$LOGFILE" 2>&1
}

post_install()
{
    mv -v $LFS/usr/bin/chroot $LFS/usr/sbin
    mkdir -pv $LFS/usr/share/man/man8
    mv -v $LFS/usr/share/man/man1/chroot.1 $LFS/usr/share/man/man8/chroot.8
    sed -i 's/"1"/"8"/' $LFS/usr/share/man/man8/chroot.8
}

source "$(dirname "$0")"/../common/common_exec
