#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=expect
VERSION=${EXPECT_VER}
TARFILE=$NAME$VERSION.tar.gz
FETCH_URL="https://prdownloads.sourceforge.net/expect/$TARFILE"
mSBU=100

patchup()
{
    cd "$TMP"/"${NAME}${VERSION}"
    cp -v configure{,.orig} >>"$LOGFILE" 2>&1
    sed 's:/usr/local/bin:/bin:' configure.orig > configure
}

configure()
{
    cd "$TMP"/"${NAME}${VERSION}"
    BUILD_PATH=$(pwd)
    ./configure --prefix=/tools \
        --with-tcl=/tools/lib \
        --with-tclinclude=/tools/include >>"$LOGFILE" 2>&1
}

build()
{
    # Bypassing this package for now due to build errors:
    # /build/tools/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: libutil.so.1, needed by /build/tmp/build/expect5.45.4/libexpect5.45.4.so, not found (try using -rpath or -rpath-link)
    #/build/tools/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: libpthread.so.0, needed by /tools/lib/libtcl8.6.so, not found (try using -rpath or -rpath-link)
    #/build/tools/bin/../lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /tools/lib/libtcl8.6.so: undefined reference to `pthread_setspecific@GLIBC_2.2.5'
    return 0
}

build_install()
{
    return 0
}

cleanup()
{
    default_cleanup "$TMP"/"${NAME}${VERSION}"
}

source "$(dirname "$0")"/../common/common_exec
