#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=dejagnu
VERSION=${DEJAGNU_VER}
TARFILE=$NAME-$VERSION.tar.gz
FETCH_URL="http://ftp.gnu.org/gnu/dejagnu/$TARFILE"
mSBU=50

configure()
{
    # Bypassing as fails due to expect failing
    return 0

    default_configure "$TMP"/"$NAME"-"$VERSION"
}

build()
{
    return 0
}

build_install()
{
    return 0
}

source "$(dirname "$0")"/../common/common_exec
