#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=findutils
VERSION=$FINDUTILS_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="https://ftp.gnu.org/gnu/findutils/$TARFILE"
mSBU=200

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    {
    ./configure \
        --prefix=/usr \
        --localstatedir=/var/lib/locate \
        --host=$LFS_TGT \
        --build=$(build-aux/config.guess)
    } >>"$LOGFILE" 2>&1
}

build_install()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    make $MAKE_JOBS DESTDIR=$LFS install >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
