#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=ncurses
VERSION=$NCURSES_VER
TARFILE=$NAME-$VERSION.tar.gz
FETCH_URL="http://ftp.gnu.org/gnu/ncurses/$TARFILE"
mSBU=600

patchup()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    sed -i s/mawk// configure
}

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    ../configure --prefix=/tools    \
        --with-shared               \
        --without-debug             \
        --without-ada               \
        --enable-widec              \
        --enable-overwrite >>"$LOGFILE" 2>&1
}

post_install()
{
    ln -svf libncursesw.so /tools/lib/libncurses.so >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
