#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=bash
VERSION=$BASH_VER
TARFILE=$NAME-$VERSION.tar.gz
FETCH_URL="http://ftp.gnu.org/gnu/bash/$TARFILE"
mSBU=400

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    ../configure --prefix=/tools \
        --without-bash-malloc >>"$LOGFILE" 2>&1
}

post_install()
{
    ln -svf bash /tools/bin/sh >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
