#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=bison
VERSION=${BISON_VER}
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/bison/$TARFILE"
mSBU=300

configure()
{
    default_configure "$TMP"/"$NAME"-"$VERSION"
}

source "$(dirname "$0")"/../common/common_exec
