#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=bzip2
VERSION=${BZIP_VER}
TARFILE=$NAME-$VERSION.tar.gz
FETCH_URL="http://anduin.linuxfromscratch.org/LFS/$TARFILE"
mSBU=70

configure()
{
    cd "$TMP"/"$NAME"-"$VERSION"
    BUILD_PATH=$(pwd)
}

build_install()
{
    cd "$BUILD_PATH"
    make PREFIX=/tools "$SILENT_MAKE" "$MAKE_JOBS" install >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
