#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=coreutils
VERSION=$COREUTILS_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/coreutils/$TARFILE"
mSBU=800

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    ../configure --prefix=/tools --enable-install-program=hostname >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
