#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=file
VERSION=$FILE_VER
TARFILE=$NAME-$VERSION.tar.gz
FETCH_URL="ftp://ftp.astron.com/pub/file/$TARFILE"
mSBU=100

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build
    ../configure --prefix=/tools \
        --disable-bzlib \
        --disable-libseccomp \
        --disable-xzlib \
        --disable-zlib >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
