#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=sed
VERSION=$SED_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/sed/$TARFILE"
mSBU=100

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    BUILD_PATH=$(pwd)

    ./configure \
        --prefix=/usr \
        --host=$LFS_TGT >>"$LOGFILE" 2>&1
}

build_install()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    make $MAKE_JOBS DESTDIR=$LFS install >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
