#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=findutils
VERSION=$FINDUTILS_VER
TARFILE=$NAME-$VERSION.tar.gz
FETCH_URL="http://ftp.gnu.org/gnu/findutils/$TARFILE"
mSBU=300

patchup()
{
    {
    cd "$WORKBENCH/$NAME-$VERSION"
    sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' gl/lib/*.c
    sed -i '/unistd/a #include <sys/sysmacros.h>' gl/lib/mountlist.c
    echo "#define _IO_IN_BACKUP 0x100" >> gl/lib/stdio-impl.h
    } >>"$LOGFILE" 2>&1
}

configure()
{
    default_configure "$WORKBENCH/$NAME-$VERSION"
}

source "$(dirname "$0")"/../common/common_exec
