#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=xz
VERSION=$XZ_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="https://tukaani.org/xz/$TARFILE"
mSBU=100

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    BUILD_PATH=$(pwd)

    ./configure \
        --prefix=/usr \
        --host=$LFS_TGT \
        --build=$(build-aux/config.guess) \
        --disable-static \
        --docdir=/usr/share/doc/xz-5.2.5 >>"$LOGFILE" 2>&1
}

build_install()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    make $MAKE_JOBS DESTDIR=$LFS install >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
