#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=gettext
VERSION=$GETTEXT_VER
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="http://ftp.gnu.org/gnu/gettext/$TARFILE"
mSBU=900

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    EMACS="no" ../gettext-tools/configure --prefix=/tools \
        --disable-shared >>"$LOGFILE" 2>&1
}

build()
{
    cd "$BUILD_PATH"
    make "$MAKE_JOBS" -C gnulib-lib >>"$LOGFILE" 2>&1
    if [ $? -ne 0 ]; then return $?;fi

    make -C intl pluralx.c >>"$LOGFILE" 2>&1
    if [ $? -ne 0 ]; then return $?;fi

    make "$MAKE_JOBS" -C src msgfmt >>"$LOGFILE" 2>&1
    if [ $? -ne 0 ]; then return $?;fi

    make "$MAKE_JOBS" -C src msgmerge >>"$LOGFILE" 2>&1
    if [ $? -ne 0 ]; then return $?;fi

    make "$MAKE_JOBS" -C src xgettext >>"$LOGFILE" 2>&1
    if [ $? -ne 0 ]; then return $?;fi
}

build_install()
{
    cd "$BUILD_PATH"
    cp -v src/{msgfmt,msgmerge,xgettext} /tools/bin >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
