#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=make
VERSION=$MAKE_VER
TARFILE=$NAME-$VERSION.tar.bz2
FETCH_URL="http://ftp.gnu.org/gnu/make/$TARFILE"
mSBU=100

patchup()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    sed -i '211,217 d; 219,229 d; 232 d' glob/glob.c
}

configure()
{
    cd "$WORKBENCH/$NAME-$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    ../configure --prefix=/tools --without-guile >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
