#!/bin/bash

source "$(dirname "$0")"/../common/common_source

NAME=Python
VERSION=${PYTHON_VER}
TARFILE=$NAME-$VERSION.tar.xz
FETCH_URL="https://www.python.org/ftp/python/3.7.2/$TARFILE"
mSBU=1500

patchup()
{
    cd "$TMP"/"$NAME"-"$VERSION"
    sed -i '/def add_multiarch_paths/a \        return' setup.py
}

configure()
{
    cd "$TMP"/"$NAME"-"$VERSION"
    mkdir build
    cd build
    BUILD_PATH=$(pwd)

    ../configure --prefix=/tools --without-ensurepip >>"$LOGFILE" 2>&1
}

source "$(dirname "$0")"/../common/common_exec
